<footer class="footer position-absolute">
            <div class="row g-0 justify-content-between align-items-center h-100 mb-3">
             <!--  <div class="col-12 col-sm-auto text-center">
                <p class="mb-0 mt-2 mt-sm-0 text-900">Thank you for creating with Phoenix<span class="d-none d-sm-inline-block"></span><span class="mx-1">|</span><br class="d-sm-none" />2022 &copy; <a href="../../../themewagon.com/themewagon_default.html">Themewagon</a></p>
              </div> -->
              <div class="col-12 col-sm-auto text-center">
                <p class="mb-0 text-600">v1.4.0</p>
              </div>
            </div>
          </footer>
<div class="modal fade" id="staticBackdroplogout" tabindex="-1" data-bs-backdrop="static" aria-labelledby="staticBackdropLabellogout" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-primary">
        <h5 class="modal-title text-white" id="staticBackdropLabellogout">Logout</h5><button class="btn p-1" type="button" data-bs-dismiss="modal" aria-label="Close"><span class="fas fa-times fs--1 text-white"></span></button>
      </div>
      <div class="modal-body">
        <p class="text-700 lh-lg mb-0">Are you sure to logout? </p>
      </div>
      <div class="modal-footer"><a href="login.php" class="btn btn-primary" type="button">Okay</a><button class="btn btn-outline-primary" type="button" data-bs-dismiss="modal">Cancel</button></div>
    </div>
  </div>
</div>
            <div class="modal fade" id="terms" tabindex="-1" aria-labelledby="terms" aria-hidden="true">
                          <div class="modal-dialog modal-dialog-scrollable">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="terms">TERMS AND CONDITIONS</h5><button class="btn p-1" type="button" data-bs-dismiss="modal" aria-label="Close"><span class="fas fa-times fs--1"></span></button>
                              </div>
                              <div class="modal-body">
                                
                                <p style='margin:0in;margin-bottom:3.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:3.0pt;margin-right:0in;margin-left:0in;text-align:justify;text-indent:.5in;background:white;'><span style="font-size:13px;line-height:115%;">The Terms and Conditions of <strong>InternshiponGo: A Responsive Web Application OJT Porta</strong>l, that encourages the College of Computing Sciences of Pangasinan State University to Register and use the system, unpaid and not principally engaged in the selling of goods and services.</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">&nbsp;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">Read Before Accessing The System.</span></strong></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">Effective Date:</span></strong><span style="font-size:13px;line-height:115%;">&nbsp;This Terms and Conditions of this system was last updated on June 9, 2022.&nbsp;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">&nbsp;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">InternshiponGo: A Responsive Web Application OJT Portal</span></strong><span style="font-size:13px;line-height:115%;">&nbsp;is owned by Pangasinan State University - Lingayen Campus addressed in Alvear Street Lingayen, Pangasinan. The following terms and conditions governed its use. By using the system, you agree to these terms and conditions. Your use and continued use of the system is strictly governed by the terms of these terms and conditions.</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><span style="font-size:13px;line-height:115%;">If you do not agree with the terms and conditions of this website, you must cease using it immediately. We reserve the right to amend, alter, or become effective immediately upon posting on <strong>InternshiponGo: A Responsive Web Application OJT Portal&nbsp;</strong>at any moment. Your continued use of the system following the posting of updates implies acknowledgement and acceptance of the amended Agreement. Except as allowed for in this paragraph, these terms and conditions cannot be amended.</span></p>
                                <ol start="1" style="margin-bottom:0in;margin-top:0in;" type="1">
                                    <li style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">A user of this system must be enrolled in Pangasinan State University-Lingayen Campus.</span></li>
                                    <li style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">You must bear responsibility for your conduct if you register or login in this system.</span></li>
                                    <li style='margin:0in;margin-bottom:.0001pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">This system is temporarily open for College of Computing Sciences Students.</span></li>
                                    <li style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">User Accounts.</span></strong></li>
                                </ol>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">The Admin provides the accounts of OJT Coordinator and Instructor.</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">Instructors of the College of Computing Sciences who supervise internships can register their students using the student number.</span></p>
                                <ol start="5" style="margin-bottom:0in;margin-top:0in;" type="1">
                                    <li style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">Use of the system</span></strong></li>
                                </ol>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">We grant OJT students of the College of Computing Sciences of Pangasinan State University - Lingayen Campus to use this system while taking their internship. While using this system, you should read and understand the restrictions on use</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;<strong>Restrictions on Use.</strong></span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><span style="font-size:13px;line-height:115%;">You agree that you will not, and will not assist or enable others to:</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">A.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> to threaten, stalk, defraud, incite, harass, or advocate the harassment of another person, or otherwise interfere with another user&apos;s use of the <strong><em>System</em></strong>;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">B.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></strong><span style="font-size:13px;line-height:115%;">Use the <strong><em>System</em></strong> to submit or transmit spam, chain letters, contests, junk email, pyramid schemes, surveys, or other mass messaging, whether commercial in nature or not;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">C.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> for promotional or commercial purposes, except as expressly allowed in writing by <strong>InternshiponGo: A Responsive Web Application OJT Portal</strong></span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">D.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> in a manner that may create a conflict of interest, such as trading reviews with other business owners or writing or soliciting shill reviews;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">E.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> for keyword spamming or to otherwise attempt to manipulate natural search results;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">F.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> to promote bigotry or discrimination against protected classes;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">G.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> to violate any third-party right, including any breach of confidence, copyright, trademark, patent, trade secret, privacy right, right of publicity, or any other intellectual property or proprietary right;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">H.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> to submit or transmit illegal content such as pornography;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">I.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Use the <strong><em>System</em></strong> to solicit personal information from minors;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">J.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> or to harm or threaten to cause harm to any person or organization;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">K.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> in violation of the Terms of Service or any applicable law;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">L.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Modify, adapt, appropriate, reproduce, distribute, translate, or create derivative works or publicly display, sell, trade, or in any way exploit the <strong><em>System</em></strong> or <strong><em>System</em></strong> Content (other than <strong><em>Your Content</em></strong>), except as expressly authorized by <strong>InternshiponGo: A Responsive Web Application OJT Portal</strong>;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">M.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;Reverse engineer any portion of the <strong><em>Site</em></strong>:</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">N.&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></strong><span style="font-size:13px;line-height:115%;">Remove or modify any copyright, trademark or other proprietary rights notice on the <strong><em>Site</em></strong> or on any materials printed or copied off of the <strong><em>System</em></strong></span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">O.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Record, process, or mine information about other users;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">P.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use site search/retrieval application, process or means to access, retrieve, scrape, or index the <strong><em>System</em></strong> or any <strong><em>System</em></strong> Content;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">Q.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Access, retrieve or index the <strong><em>System</em></strong> to for purposes of constructing or populating a searchable database of business reviews;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;text-indent:.5in;background:white;'><strong><span style="font-size:13px;line-height:115%;">R.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Reformat or frame any portion of the <strong><em>System</em></strong>;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">S.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Take any action that imposes, or may impose an unreasonable or disproportionately large load on the technology infrastructure on <strong>InternshiponGo: A Responsive Web Application OJT Portal;</strong></span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">T.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Attempt to gain unauthorized access to the <strong><em>System</em></strong>, user accounts, computer systems or networks connected to the <strong><em>System</em></strong> through hacking, password mining or any other means;</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;margin-top:0in;margin-right:0in;margin-left:.5in;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">U.</span></strong><span style="font-size:13px;line-height:115%;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Use the <strong><em>System</em></strong> or any <strong><em>System</em></strong> Content to transmit any computer viruses, worms, defects, Trojan horses or other items of a destructive nature (collectively,<em>&nbsp;Viruses</em>); use any device, software or routine that interferes with the proper working of the <strong><em>Site</em></strong>, or otherwise attempt to interfere with the proper working of the <strong><em>System</em></strong>; make excessive traffic demands; use the <strong><em>System</em></strong> to violate the security of any computer network, crack passwords or security encryption codes; disrupt or interfere with the security of, or otherwise cause harm to, the <strong><em>System</em></strong> or <strong><em>System</em></strong> Content; remove, circumvent, disable, damage or otherwise interfere with any security-related features of the <strong><em>System</em></strong>, features that prevent or restrict the use of <strong><em>System</em></strong> Content, or features that enforce limitations on the use of the <strong><em>System</em></strong>.</span></p>
                                <p style='margin:0in;margin-bottom:6.0pt;line-height:115%;font-size:15px;font-family:"Arial",sans-serif;text-align:justify;background:white;'><strong><span style="font-size:13px;line-height:115%;">&nbsp;</span></strong></p>
                              </div>
                              <div class="modal-footer"><button class="btn btn-primary" type="button" data-bs-dismiss="modal">Okay</button><button class="btn btn-outline-primary" type="button" data-bs-dismiss="modal">Cancel</button></div>
                            </div>
                          </div>
                        </div>